import type Database from "bun:sqlite";
import { EP_IDS, NGE_SHOW } from "./ids";

export function initializeEpisodes(db: Database) {
  db.run(`
    CREATE TABLE IF NOT EXISTS episodes (
      id TEXT PRIMARY KEY,
      show_id TEXT NOT NULL,
      episode_number INTEGER NOT NULL,
      title TEXT NOT NULL,
      title_japanese TEXT NOT NULL,
      air_date TEXT NOT NULL,
      synopsis TEXT NOT NULL,
      FOREIGN KEY (show_id) REFERENCES shows(id)
    )
  `);

  const insertEpisode = db.prepare(
    "INSERT INTO episodes (id, show_id, episode_number, title, title_japanese, air_date, synopsis) VALUES (?, ?, ?, ?, ?, ?, ?)"
  );

  const episodes = [
    {
      id: EP_IDS.ep1,
      showId: NGE_SHOW,
      episodeNumber: 1,
      title: "Angel Attack",
      titleJapanese: "使徒、襲来",
      airDate: "1995-10-04",
      synopsis: "Shinji Ikari arrives in Tokyo-3 and is recruited by his estranged father Gendo to pilot Evangelion Unit-01 against the Angel Sachiel.",
    },
    {
      id: EP_IDS.ep2,
      showId: NGE_SHOW,
      episodeNumber: 2,
      title: "The Beast",
      titleJapanese: "見知らぬ、天井",
      airDate: "1995-10-11",
      synopsis: "Shinji wakes up in the hospital after his first battle and struggles to come to terms with his new role as an Eva pilot.",
    },
    {
      id: EP_IDS.ep3,
      showId: NGE_SHOW,
      episodeNumber: 3,
      title: "A Transfer",
      titleJapanese: "鳴らない、電話",
      airDate: "1995-10-18",
      synopsis: "Shinji begins attending school in Tokyo-3 and meets his classmates Toji and Kensuke, while struggling to connect with others.",
    },
    {
      id: EP_IDS.ep4,
      showId: NGE_SHOW,
      episodeNumber: 4,
      title: "Hedgehog's Dilemma",
      titleJapanese: "雨、逃げ出した後",
      airDate: "1995-10-25",
      synopsis: "After a difficult battle, Shinji runs away from NERV and wanders Tokyo-3, questioning his purpose and relationships.",
    },
    {
      id: EP_IDS.ep5,
      showId: NGE_SHOW,
      episodeNumber: 5,
      title: "Rei I",
      titleJapanese: "レイ、心のむこうに",
      airDate: "1995-11-01",
      synopsis: "Shinji learns more about the mysterious Rei Ayanami and witnesses her cold relationship with his father during a reactivation test of Unit-00.",
    },
    {
      id: EP_IDS.ep6,
      showId: NGE_SHOW,
      episodeNumber: 6,
      title: "Rei II",
      titleJapanese: "決戦、第3新東京市",
      airDate: "1995-11-08",
      synopsis: "Shinji and Rei must work together to defeat the Angel Ramiel, which is drilling through the Geofront toward NERV headquarters.",
    },
    {
      id: EP_IDS.ep7,
      showId: NGE_SHOW,
      episodeNumber: 7,
      title: "A Human Work",
      titleJapanese: "人の造りしもの",
      airDate: "1995-11-15",
      synopsis: "NERV faces political pressure when the UN-backed Jet Alone project threatens to replace the Evangelions.",
    },
    {
      id: EP_IDS.ep8,
      showId: NGE_SHOW,
      episodeNumber: 8,
      title: "Asuka Strikes!",
      titleJapanese: "アスカ、来日",
      airDate: "1995-11-22",
      synopsis: "The Second Child, Asuka Langley Soryu, arrives from Germany with Evangelion Unit-02 and immediately clashes with Shinji.",
    },
    {
      id: EP_IDS.ep9,
      showId: NGE_SHOW,
      episodeNumber: 9,
      title: "Both of You, Dance Like You Want to Win!",
      titleJapanese: "瞬間、心、重ねて",
      airDate: "1995-11-29",
      synopsis: "Shinji and Asuka must learn to synchronize their movements to defeat the Angel Israfel, which can split into two separate entities.",
    },
    {
      id: EP_IDS.ep10,
      showId: NGE_SHOW,
      episodeNumber: 10,
      title: "Magmadiver",
      titleJapanese: "マグマダイバー",
      airDate: "1995-12-06",
      synopsis: "Asuka pilots Unit-02 into a volcano to capture an Angel embryo, but the mission goes awry when the Angel hatches.",
    },
    {
      id: EP_IDS.ep11,
      showId: NGE_SHOW,
      episodeNumber: 11,
      title: "The Day Tokyo-3 Stood Still",
      titleJapanese: "静止した闇の中で",
      airDate: "1995-12-13",
      synopsis: "A massive power outage cripples Tokyo-3 and NERV, leaving the pilots trapped and vulnerable when an Angel attacks.",
    },
    {
      id: EP_IDS.ep12,
      showId: NGE_SHOW,
      episodeNumber: 12,
      title: "She Said, 'Don't Make Others Suffer for Your Personal Hatred.'",
      titleJapanese: "奇跡の価値は",
      airDate: "1995-12-20",
      synopsis: "Misato confronts her past during a mission to destroy an Angel in orbit, reflecting on her father and her motivations.",
    },
    {
      id: EP_IDS.ep13,
      showId: NGE_SHOW,
      episodeNumber: 13,
      title: "Lilliputian Hitcher",
      titleJapanese: "使徒、侵入",
      airDate: "1995-12-27",
      synopsis: "A microscopic Angel infiltrates the MAGI supercomputer system, forcing Ritsuko to confront her mother's legacy.",
    },
    {
      id: EP_IDS.ep14,
      showId: NGE_SHOW,
      episodeNumber: 14,
      title: "Weaving a Story",
      titleJapanese: "ゼーレ、魂の座",
      airDate: "1996-01-03",
      synopsis: "A recap episode interspersed with new scenes showing SEELE's perspective and Rei's mysterious inner world.",
    },
    {
      id: EP_IDS.ep15,
      showId: NGE_SHOW,
      episodeNumber: 15,
      title: "Those Women Longed for the Touch of Others' Lips, and Thus Invited Their Kisses.",
      titleJapanese: "嘘と沈黙",
      airDate: "1996-01-10",
      synopsis: "Romantic tensions arise as Kaji returns to Tokyo-3, while Shinji experiences his first kiss with Asuka.",
    },
    {
      id: EP_IDS.ep16,
      showId: NGE_SHOW,
      episodeNumber: 16,
      title: "Splitting of the Breast",
      titleJapanese: "死に至る病、そして",
      airDate: "1996-01-17",
      synopsis: "Shinji is absorbed into the Angel Leliel and experiences a psychological journey through his own mind.",
    },
    {
      id: EP_IDS.ep17,
      showId: NGE_SHOW,
      episodeNumber: 17,
      title: "Fourth Child",
      titleJapanese: "四人目の適格者",
      airDate: "1996-01-24",
      synopsis: "NERV identifies the Fourth Child for the new Evangelion Unit-03, with the choice having profound implications.",
    },
    {
      id: EP_IDS.ep18,
      showId: NGE_SHOW,
      episodeNumber: 18,
      title: "Ambivalence",
      titleJapanese: "命の選択を",
      airDate: "1996-01-31",
      synopsis: "Unit-03 is taken over by an Angel during its activation test, forcing Shinji into an impossible situation.",
    },
    {
      id: EP_IDS.ep19,
      showId: NGE_SHOW,
      episodeNumber: 19,
      title: "Introjection",
      titleJapanese: "男の戰い",
      airDate: "1996-02-07",
      synopsis: "After refusing to pilot, Shinji watches helplessly as Unit-01 goes berserk against the powerful Angel Zeruel.",
    },
    {
      id: EP_IDS.ep20,
      showId: NGE_SHOW,
      episodeNumber: 20,
      title: "Weaving a Story 2: Oral Stage",
      titleJapanese: "心のかたち 人のかたち",
      airDate: "1996-02-14",
      synopsis: "Shinji is absorbed into Unit-01 after its awakening, and NERV attempts to recover him while exploring his memories.",
    },
    {
      id: EP_IDS.ep21,
      showId: NGE_SHOW,
      episodeNumber: 21,
      title: "He Was Aware That He Was Still a Child",
      titleJapanese: "ネルフ、誕生",
      airDate: "1996-02-21",
      synopsis: "Flashbacks reveal the history of NERV, the truth about the Second Impact, and the complex relationships between key personnel.",
    },
    {
      id: EP_IDS.ep22,
      showId: NGE_SHOW,
      episodeNumber: 22,
      title: "Don't Be.",
      titleJapanese: "せめて、人間らしく",
      airDate: "1996-02-28",
      synopsis: "Asuka's sync rate drops as she battles the Angel Arael, which psychologically attacks her, revealing her traumatic past.",
    },
    {
      id: EP_IDS.ep23,
      showId: NGE_SHOW,
      episodeNumber: 23,
      title: "Rei III",
      titleJapanese: "涙",
      airDate: "1996-03-06",
      synopsis: "The truth about Rei Ayanami is revealed as she sacrifices herself to destroy the Angel Armisael.",
    },
    {
      id: EP_IDS.ep24,
      showId: NGE_SHOW,
      episodeNumber: 24,
      title: "The Beginning and the End, or 'Knockin' on Heaven's Door'",
      titleJapanese: "最後のシ者",
      airDate: "1996-03-13",
      synopsis: "Kaworu Nagisa, the Fifth Child, befriends Shinji but is revealed to be the final Angel, Tabris.",
    },
    {
      id: EP_IDS.ep25,
      showId: NGE_SHOW,
      episodeNumber: 25,
      title: "Do You Love Me?",
      titleJapanese: "終わる世界",
      airDate: "1996-03-20",
      synopsis: "As Instrumentality begins, the characters undergo psychological introspection, questioning their existence and relationships.",
    },
    {
      id: EP_IDS.ep26,
      showId: NGE_SHOW,
      episodeNumber: 26,
      title: "Take Care of Yourself.",
      titleJapanese: "世界の中心でアイを叫んだけもの",
      airDate: "1996-03-27",
      synopsis: "The series concludes with Shinji's internal journey toward self-acceptance, culminating in a message of hope and congratulations.",
    },
  ];

  for (const episode of episodes) {
    insertEpisode.run(
      episode.id,
      episode.showId,
      episode.episodeNumber,
      episode.title,
      episode.titleJapanese,
      episode.airDate,
      episode.synopsis
    );
  }
}
