name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: "deno install"

      - name: Generate database schema
        run: "deno run db:generate"

      - name: Apply migrations
        run: "deno run db:deploy"

      - name: Seed database
        run: "deno run db:seed"

      - name: Apply Prisma patch
        run: "deno run prisma:patch"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "nge-api"
          entrypoint: "src/main.ts"
