name: Unit tests
on:
  pull_request:

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    outputs:
      COVERAGE_REPORT_NAME: ${{ steps.normalise_name.outputs.COVERAGE_REPORT_NAME }}
    strategy:
      matrix:
        branch:
          - ${{ github.head_ref }}
          - "main"

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js 22.9.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.9.0
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run vitest
        run: pnpm run test:coverage

      - name: Normalise coverage report name
        id: normalise_name
        run: |
          branch="${{ matrix.branch }}"
          echo "COVERAGE_REPORT_NAME=${branch//\//-}" >> $GITHUB_OUTPUT

      - name: "Save unit test coverage report as artifact"
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ steps.normalise_name.outputs.COVERAGE_REPORT_NAME }}
          path: coverage

  report-coverage:
    needs: unit-tests
    runs-on: ubuntu-latest
    env:
      COVERAGE_REPORT_NAME: "${{ needs.unit-tests.outputs.COVERAGE_REPORT_NAME }}"

    steps:
      - name: "Download PR test coverage report"
        uses: actions/download-artifact@v4
        with:
          name: coverage-${{ env.COVERAGE_REPORT_NAME }}
          path: coverage

      - name: "Download main test coverage report"
        uses: actions/download-artifact@v4
        with:
          name: coverage-main
          path: coverage-main

      - name: "Report Coverage"
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          json-summary-compare-path: coverage-main/coverage-summary.json
